name: Deploy Node App
on:
  push:
    branches: [ zikra-new ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 165.22.162.119
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/node-app
            git checkout zikra-new
            git pull origin zikra-new
            cd Zikra-site/server
            npm install --production
            pm2 restart node-app || pm2 start app.js --name "node-app"